### ISSUE TITLE
Improving reproducibility of the repo!

### ISSUE THREAD

**Issue by mxochicale** [HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course#15]
* [x] Tidy up [Summary and Setup](https://healthbioscienceideas.github.io/Medical-Image-Registration-Short-Course/)    * [x] adds cloning instructions for new users (create github user name, SSH keys, etc). [9969509](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/commit/99695095d9e485e35254b6c0c6ff6ea402746ce4)
* [x] Main README is kind of empty, we might like to add few details for better readability and accessibility of the content, contributors, maintainers, licence, etc. 
  * [x]  adds CODE_OF_CONDUCT
* [x] Great to have [CONTRIBUTING.md](https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/blob/main/CONTRIBUTING.md#how-to-contribute) guidelines but needs to be updated with the correct links and emails.
   * [x]  Adds templates 553b747
* [x] Add warning for #10 63ba3c2
* [x] Tidies up preview of sandpaper and its installation of requirements   Mention #14 
98798b7
* [x] Adds Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.
* [x] Adds "Branch protection rules" for main  https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/settings/branch_protection_rules/new 
```
* Protect matching branches
Require a pull request before merging
When enabled, all commits must be made to a non-protected branch and submitted via a pull request before they can be merged into a branch that matches this rule.
Require approvals
When enabled, pull requests targeting a matching branch require a number of approvals and no changes requested before they can be merged.
* Rules applied to everyone including administrators
Allow force pushes
Permit force pushes for all users with push access.
Everyone
```
* [x] hosting data for exercise 4 https://github.com/HealthBioscienceIDEAS/Medical-Image-Registration-Short-Course/issues/7#issuecomment-2168419240 Nothing to do here as we agree to add explicit details on how to download and use datasets for this course!
